# Generated by Django 5.0.6 on 2024-06-18 05:20

import personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(validators=[personas.models.validate_age]),
        ),
    ]
